### ISSUE TITLE
App with this dependency cannot be installed in XCode 15.3

### ISSUE THREAD

**Issue by pa-rw** [decentralised-dataexchange/PresentationExchangeSdkiOS#1]
Probably due to this issue: https://github.com/golang/go/issues/66018

Reproduce:
- Create new iOS project in XCode 15.3.
- Add dependency according to README.
- Run on device or simulator.

**Comment by georgepadayatti** [comment]
We will check this internally and revert to the same.

**Comment by josmilan** [comment]
This is fixed in 2024.8.1 release
